title: Little Doodles
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3095238
  brandStrength: 0.6560555738396943
  lightness: 0.3007519
  brandColors:
    - '#352526'
    - '#434327'
    - '#FFAA63'
    - '#8B603E'
    - '#C5A151'
  rhythmicContrast: 0.3120301
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: little doodles
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8013784
layout_spectrum: 0.462406
